Refactor pt.1 ma->ot

diff --git a/ot_redundancy/usr/bin/ot-connection-test b/ot_redundancy/usr/bin/ot-connection-test
--- a/ot_redundancy/usr/bin/ot-connection-test
+++ b/ot_redundancy/usr/bin/ot-connection-test
@@ -4,11 +4,11 @@
 ################################################################################
 
 ## Test if conf exist so we don't garble stuff
-if [ -f /etc/odoo/ma-redundancy-sync.conf ];
+if [ -f /etc/odoo/ot-redundancy-sync.conf ];
 then
-  source /etc/odoo/ma-redundancy-sync.conf
+  source /etc/odoo/ot-redundancy-sync.conf
 else
-  echo "Configuration /etc/odoo/ma-redundancy-sync.conf not found" 1>&2
+  echo "Configuration /etc/odoo/ot-redundancy-sync.conf not found" 1>&2
   exit -1
 fi
 if [ ! $SYNCMODE = "on" ]; then
@@ -17,7 +17,7 @@ if [ ! $SYNCMODE = "on" ]; then
 fi
 
 useage(){
-    echo "Usage: sudo ma-connection-test"
+    echo "Usage: sudo ot-connection-test"
     echo "The user running the program need to be root as the sync-scripts are intended to be run as root."
 }
 
@@ -49,5 +49,5 @@ else
 fi
 
 ## -------------------------------------------------------------------------- ##
-ma-write-summary $0
+ot-write-summary $0
 exit 0
