Sync pip3 modules

diff --git a/ot_redundancy/usr/bin/ot-sync-from-source b/ot_redundancy/usr/bin/ot-sync-from-source
--- a/ot_redundancy/usr/bin/ot-sync-from-source
+++ b/ot_redundancy/usr/bin/ot-sync-from-source
@@ -10,10 +10,18 @@ Y='\033[1;33m'
 G='\033[0;32m'
 B='\033[0;34m'
 
-echo "DB-sync is made via WAL files and is excluded from this message"
+echo "DB replication is made separately from this script and is excluded from this message"
 
 echo "Syncing installed apt packages ..."
 ot-apt-sync
+if [ $? -eq 0 ]; then
+    echo -e "${G}Success"
+else
+    echo -e "${R}Failure"
+fi
+
+echo "Syncing installed pip3 packages ..."
+ot-pip-sync
 if [ $? -eq 0 ]; then
     echo -e "${G}Success"
 else
